version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: "postgresql://urlshortener:password@postgres:5432/url_shortener?schema=public"
  #     JWT_SECRET: "your-super-secret-jwt-key-here"
  #     PORT: 3000
  #     ENABLE_SWAGGER: "true"
  #     APP_DOMAIN: "localhost:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

volumes:
  postgres_data: